# Generated by Django 3.1.4 on 2020-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=35)),
                ('Lname', models.CharField(max_length=35)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Enr', models.CharField(max_length=25)),
                ('Uni', models.CharField(max_length=100)),
            ],
        ),
    ]
